"""
VirtualOutfit AI - Image Generation Pipeline (FASHN.ai)

This module implements a pipeline for generating AI fashion photography using FASHN.ai:
1. Product Analysis - Detect product category from image
2. Preview Generation - Generate on-model image using FASHN.ai
3. Ultra Quality Generation - High quality generation with enhanced settings

FASHN.ai Product-to-Model API turns flat-lay product photos into realistic on-model images.
"""

import os
import base64
import logging
import httpx
import asyncio
from typing import Optional, Dict, Any

from dotenv import load_dotenv
from fashn_provider import get_fashn_provider, FashnProvider

# Load environment variables
load_dotenv()

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# FASHN provider instance
_fashn_provider: Optional[FashnProvider] = None


def get_provider() -> FashnProvider:
    """Get or initialize the FASHN provider."""
    global _fashn_provider
    if _fashn_provider is None:
        _fashn_provider = get_fashn_provider()
        if not _fashn_provider.api_key:
            raise ValueError("FASHN_API_KEY is not configured")
        logger.info("FASHN.ai provider loaded successfully")
    return _fashn_provider


def initialize_services():
    """Explicitly initialize services for startup checks."""
    logger.info("Initializing FASHN.ai services...")
    try:
        provider = get_provider()
        logger.info(f"FASHN.ai services initialized successfully (API key: {provider.api_key[:10]}...)")
    except Exception as e:
        logger.warning(f"FASHN.ai initialization deferred: {e}")
        logger.warning("The server will start, but image generation will fail until API key is configured.")


# ============================================
# STEP 1: Product Category Detection
# ============================================

def detect_category(product_description: str, generation_type: str = "fashion") -> str:
    """
    Detect the product category from description for FASHN.ai API.
    
    FASHN.ai categories: tops, bottoms, dresses, outerwear, full-body, accessories
    """
    description_lower = product_description.lower()
    
    # Check for specific categories
    if any(word in description_lower for word in ['dress', 'gown', 'romper', 'jumpsuit']):
        return 'dresses'
    elif any(word in description_lower for word in ['pants', 'jeans', 'shorts', 'skirt', 'trousers', 'leggings']):
        return 'bottoms'
    elif any(word in description_lower for word in ['jacket', 'coat', 'blazer', 'cardigan', 'hoodie', 'sweater']):
        return 'outerwear'
    elif any(word in description_lower for word in ['necklace', 'bracelet', 'earring', 'ring', 'watch', 'bag', 'hat', 'scarf']):
        return 'accessories'
    elif any(word in description_lower for word in ['suit', 'outfit', 'set', 'coord']):
        return 'full-body'
    else:
        # Default to tops for most clothing items
        return 'tops'


async def analyze_outfit_image(
    image_data: bytes,
    mime_type: str = "image/jpeg",
    product_description: str = "",
    generation_type: str = "fashion"
) -> str:
    """
    Step 1: Analyze product image and construct description.
    
    For FASHN.ai, we pass the image directly - this returns category and prompt info.
    """
    category = detect_category(product_description, generation_type)
    
    # Build a prompt/description for logging
    prompt = f"FASHN.ai Product-to-Model: {product_description or 'Fashion product'} (category: {category})"
    
    logger.info(f"Detected category: {category} for product: {product_description[:50]}...")
    
    return prompt


# ============================================
# STEP 2: Preview Generation (FASHN.ai)
# ============================================

async def generate_preview(
    prompt: str,
    aspect_ratio: str = "3:4",
    negative_prompt: str = "",
    image_base64_input: Optional[str] = None
) -> dict:
    """
    Step 2: Generate a preview image using FASHN.ai Product-to-Model.
    
    Note: FASHN.ai uses product images directly, not text prompts.
    For direct prompt-based generation, we'll use a placeholder approach.
    """
    provider = get_provider()
    
    # If we have an input image, use FASHN.ai
    if image_base64_input:
        # Detect category from prompt
        category = detect_category(prompt)
        
        result = await provider.generate_and_wait(
            product_image_base64=image_base64_input,
            prompt=prompt,
            category=category,
            mode="generate",
            timeout_seconds=120
        )
        
        # Get the output image URL
        output_images = result.get("output", [])
        if not output_images:
            raise ValueError("No images generated by FASHN.ai")
        
        # Download the first output image and convert to base64
        image_url = output_images[0]
        async with httpx.AsyncClient() as client:
            img_response = await client.get(image_url, timeout=30.0)
            if img_response.status_code != 200:
                raise ValueError(f"Failed to download generated image: {img_response.status_code}")
            
            image_bytes = img_response.content
            image_base64 = base64.b64encode(image_bytes).decode('utf-8')
        
        return {
            "image_base64": image_base64,
            "mime_type": "image/jpeg",
            "model_used": "fashn-product-to-model",
            "quality": "preview"
        }
    else:
        # No image provided - can't use FASHN.ai for text-only generation
        raise ValueError("FASHN.ai requires a product image. Please upload a product photo.")


# ============================================
# STEP 3: Ultra Quality Generation (FASHN.ai)
# ============================================

async def generate_ultra_quality(
    prompt: str,
    aspect_ratio: str = "3:4",
    negative_prompt: str = "",
    image_base64_input: Optional[str] = None
) -> dict:
    """
    Step 3: Generate ultra-quality image using FASHN.ai with enhanced settings.
    """
    provider = get_provider()
    
    if image_base64_input:
        category = detect_category(prompt)
        
        # Use enhanced settings for ultra quality
        result = await provider.run_product_to_model(
            product_image_base64=image_base64_input,
            prompt=prompt,
            category=category,
            mode="generate",
            num_samples=1,
            adjust_hands=True,  # Better hand positioning
            restore_background=False
        )
        
        prediction_id = result.get("id")
        if not prediction_id:
            raise ValueError("No prediction ID returned from FASHN.ai")
        
        # Wait for completion with longer timeout for ultra quality
        elapsed = 0
        timeout_seconds = 180  # 3 minutes for ultra quality
        poll_interval = 5
        
        while elapsed < timeout_seconds:
            status = await provider.get_status(prediction_id)
            state = status.get("status")
            
            if state == "completed":
                output_images = status.get("output", [])
                if not output_images:
                    raise ValueError("No images generated by FASHN.ai")
                
                # Download and convert to base64
                image_url = output_images[0]
                async with httpx.AsyncClient() as client:
                    img_response = await client.get(image_url, timeout=30.0)
                    if img_response.status_code != 200:
                        raise ValueError(f"Failed to download generated image: {img_response.status_code}")
                    
                    image_bytes = img_response.content
                    image_base64 = base64.b64encode(image_bytes).decode('utf-8')
                
                return {
                    "image_base64": image_base64,
                    "mime_type": "image/jpeg",
                    "model_used": "fashn-product-to-model-ultra",
                    "quality": "ultra"
                }
            elif state == "failed":
                raise ValueError(f"FASHN.ai generation failed: {status.get('error', 'Unknown error')}")
            
            await asyncio.sleep(poll_interval)
            elapsed += poll_interval
        
        raise TimeoutError("FASHN.ai ultra generation timed out")
    else:
        raise ValueError("FASHN.ai requires a product image for ultra quality generation.")


# ============================================
# Combined Pipeline Function
# ============================================

async def generate_outfit_image(
    image_data: bytes,
    mime_type: str = "image/jpeg",
    product_description: str = "",
    generation_type: str = "fashion",
    quality: str = "preview",
    form_data: dict = None,
    aspect_ratio: str = "3:4"
) -> dict:
    """
    Complete pipeline: Analyze → Generate with FASHN.ai.
    
    Args:
        image_data: Raw bytes of the product image
        mime_type: MIME type of the image
        product_description: User's description of the product
        generation_type: Type of generation (fashion, jewellery, flatlay)
        quality: "preview" or "ultra"
        form_data: Additional form selections
        aspect_ratio: Desired aspect ratio
    
    Returns:
        Dict with generated image and metadata
    """
    
    # Convert image bytes to base64
    image_base64 = base64.b64encode(image_data).decode('utf-8')
    
    # Detect category
    category = detect_category(product_description, generation_type)
    
    # Build prompt for logging
    prompt = await analyze_outfit_image(
        image_data=image_data,
        mime_type=mime_type,
        product_description=product_description,
        generation_type=generation_type
    )
    
    # Generate with FASHN.ai
    if quality == "ultra":
        result = await generate_ultra_quality(
            prompt=prompt,
            aspect_ratio=aspect_ratio,
            image_base64_input=image_base64
        )
    else:
        result = await generate_preview(
            prompt=prompt,
            aspect_ratio=aspect_ratio,
            image_base64_input=image_base64
        )
    
    # Add prompts to result
    result["base_prompt"] = prompt
    result["enhanced_prompt"] = f"{prompt} (category: {category})"
    result["category"] = category
    
    return result
